server:  port: ${eureka.server.port}
#Eureka Standalone Server
eureka:   client:    register-with-eureka: false
    fetch-registry: false
    service-url:      defaultZone: ${eureka.client.service-url.defaultZone}